# Load the data

In [1]:
import pandas as pd
import numpy as np
import random

In [9]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [16]:
len(train), len(test)

(3711, 1000)

In [13]:
len(train.columns), len(test.columns)

(38, 37)

In [10]:
train.head()

,DURACIÓN_HOSPITAL,ESTADO,MI,PVD,IC,CVD,DEMENT,EPOC,DMS,DMC,...,ALT,LEUCOCITOS,LINFOCITOS,IL6,FERRITINA,CRP,PROCALCITONINA,TROPONINA,NACIONALIDAD,FECHA_INGRESO
0,1,recuperado,0,0,0,0,0,0,0,0,...,14.0,5.6,1.4,NaN,NaN,0.4999,NaN,0.01,0,05-08-2020 03:32:01
1,2,fallecido,0,1,0,0,0,0,0,0,...,32.0,12.2,0.3,NaN,885.0,14.9000,0.6,1.20,1,05-25-2020 11:15:37
2,2,fallecido,0,1,1,1,1,1,0,0,...,18.0,6.1,0.5,324.1,629.0,33.9000,1.2,NaN,1,05-11-2020 12:20:12
3,15,recuperado,1,0,0,0,1,0,0,1,...,17.0,3.7,0.5,NaN,816.0,18.4000,7.3,0.05,0,05-23-2020 11:12:19
4,9,recuperado,0,0,0,0,0,0,0,0,...,28.0,5.7,1.4,39.4,1691.0,11.6000,NaN,0.01,0,05-25-2020 01:44:55

In [11]:
test.head()

,DURACIÓN_HOSPITAL,MI,PVD,IC,CVD,DEMENT,EPOC,DMS,DMC,ENFERMEDAD_RENAL,...,ALT,LEUCOCITOS,LINFOCITOS,IL6,FERRITINA,CRP,PROCALCITONINA,TROPONINA,NACIONALIDAD,FECHA_INGRESO
0,12,1,0,1,0,0,0,0,1,1,...,143.0,7.5,1.1,1133.20,1920.0,7.1,0.2,0.01,0,05-01-2020 11:17:47
1,2,0,0,0,0,0,0,0,0,0,...,28.0,6.8,1.6,NaN,NaN,NaN,NaN,0.01,3,04-30-2020 02:22:59
2,3,0,0,0,1,0,0,0,0,0,...,26.0,11.0,2.0,NaN,NaN,19.9,0.2,NaN,1,05-18-2020 07:40:37
3,4,0,0,0,0,0,0,0,0,0,...,52.0,8.9,0.7,439.86,1476.0,29.3,NaN,0.53,3,05-07-2020 10:32:27
4,6,0,0,0,0,0,0,0,0,0,...,53.0,9.3,0.5,NaN,NaN,0.0,0.0,NaN,0,05-21-2020 11:44:27

# Random guesser model

In [14]:
def random_predict(test):
    return [random.choice(['recuperado', 'fallecido']) for _ in range(len(test))]

# Make a sample submission

In [15]:
sample_submission = pd.DataFrame({'ID': list(range(0, len(test))), 'ESTADO': random_predict(test)})

In [ ]:
sample_submission.to_csv('sample_submission.csv', index=False)

In [ ]:
!kaggle competitions submit -c mlut2023-covid-19-mortality-prediction -f sample_submission.csv -m "Sample submission test"